name: ci

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FAST_TRAIN: "1"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      
      # - name: Generate synthetic data
      #   run: python generate_dataset.py

      - name: Train model (produce artifacts)
        run: python -m src.train

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Run tests (verbose)
        run: |
          python -V
          ls -la
          ls -la model || true
          pytest -vv -s
